import {onAuthStateChanged,signOut} from "https://www.gstatic.com/firebasejs/9.22.2/firebase-auth.js";
import {doc,getDoc,setDoc} from "https://www.gstatic.com/firebasejs/9.22.2/firebase-firestore.js";
import {auth,db} from "./firebase_config.js";
const widget=document.querySelector("[data-profile-widget]");
if(widget){
const trigger=widget.querySelector(".profile-trigger"),menu=widget.querySelector("[data-profile-menu]"),name_el=widget.querySelector("[data-profile-name]"),avatar_el=widget.querySelector("[data-profile-avatar]");
const avatars=["△","🚀","🤖","🎮","🌙","⚡","🪐","👾","🐉","🦊","🐺","🐱"];let current_user=null,selected_avatar="△";
const dialog=document.createElement("dialog");dialog.className="profile-dialog";dialog.innerHTML=`<form class="profile-form"><div class="profile-dialog-head"><div><h2>Your Profile</h2><p>Choose how you appear around Stellaz.</p></div><button class="profile-close" type="button">×</button></div><div class="profile-field"><label for="profile_username">Username</label><input id="profile_username" maxlength="24" autocomplete="nickname" required></div><span class="profile-avatar-label">Profile picture</span><div class="profile-avatar-options">${avatars.map(a=>`<button class="avatar-choice" type="button" data-avatar="${a}">${a}</button>`).join("")}</div><button class="profile-save" type="submit">Save Profile</button><p class="profile-message" aria-live="polite"></p></form>`;document.body.appendChild(dialog);
const input=dialog.querySelector("#profile_username"),message=dialog.querySelector(".profile-message");
function render(n,a){name_el.textContent=n||"Account";avatar_el.textContent=a||"△"}function select(a){selected_avatar=a;dialog.querySelectorAll(".avatar-choice").forEach(b=>b.classList.toggle("selected",b.dataset.avatar===a))}
trigger.addEventListener("click",e=>{e.stopPropagation();menu.hidden=!menu.hidden;trigger.setAttribute("aria-expanded",String(!menu.hidden))});document.addEventListener("click",e=>{if(!widget.contains(e.target)){menu.hidden=true;trigger.setAttribute("aria-expanded","false")}});
widget.querySelector("[data-profile-edit]").addEventListener("click",()=>{menu.hidden=true;message.textContent="";dialog.showModal()});widget.querySelector("[data-profile-logout]").addEventListener("click",async()=>{await signOut(auth);window.location.href="../index.html"});
dialog.querySelector(".profile-close").addEventListener("click",()=>dialog.close());dialog.querySelectorAll(".avatar-choice").forEach(b=>b.addEventListener("click",()=>select(b.dataset.avatar)));
dialog.querySelector(".profile-form").addEventListener("submit",async e=>{e.preventDefault();if(!current_user)return;const display_name=input.value.trim();if(!display_name)return;message.textContent="Saving...";try{await setDoc(doc(db,"users",current_user.uid),{display_name,profile_avatar:selected_avatar},{merge:true});render(display_name,selected_avatar);message.textContent="Profile saved.";setTimeout(()=>dialog.close(),450)}catch(error){console.error(error);message.textContent="Unable to save profile."}});
onAuthStateChanged(auth,async user=>{if(!user){window.location.href="../index.html";return}current_user=user;const fallback=user.email?.split("@")[0]||"Account";try{const snap=await getDoc(doc(db,"users",user.uid)),profile=snap.exists()?snap.data():{};const display_name=profile.display_name||fallback;selected_avatar=profile.profile_avatar||"△";input.value=display_name;select(selected_avatar);render(display_name,selected_avatar)}catch(error){console.error(error);input.value=fallback;render(fallback,"△")}});
}