create table public.manga_library (
    id bigint generated by default as identity primary key,
    user_id text not null default (auth.jwt() ->> 'sub'::text),
    anilist_id integer not null,
    title text not null,
    title_romaji text,
    title_native text,
    synonyms text[] not null default '{}',
    country_of_origin text,
    media_kind text not null default 'Manga'
        check (media_kind in ('Manga','Manhwa','Manhua','Other')),
    format text,
    publication_status text,
    user_status text not null default 'reading'
        check (user_status in ('reading','completed','on_hold','dropped','plan_to_read')),
    chapters_read integer not null default 0 check (chapters_read >= 0),
    total_chapters integer check (total_chapters is null or total_chapters >= 0),
    volumes_read integer not null default 0 check (volumes_read >= 0),
    total_volumes integer check (total_volumes is null or total_volumes >= 0),
    my_rating numeric check (my_rating is null or (my_rating >= 0 and my_rating <= 10)),
    anilist_score integer check (anilist_score is null or (anilist_score >= 0 and anilist_score <= 100)),
    poster_url text,
    banner_url text,
    description text,
    genres text[] not null default '{}',
    site_url text,
    start_date date,
    end_date date,
    added_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint manga_library_user_anilist_unique unique (user_id, anilist_id)
);

alter table public.manga_library enable row level security;

create policy "Users can read own manga"
on public.manga_library for select
to authenticated
using (user_id = (auth.jwt() ->> 'sub'::text));

create policy "Users can insert own manga"
on public.manga_library for insert
to authenticated
with check (user_id = (auth.jwt() ->> 'sub'::text));

create policy "Users can update own manga"
on public.manga_library for update
to authenticated
using (user_id = (auth.jwt() ->> 'sub'::text))
with check (user_id = (auth.jwt() ->> 'sub'::text));

create policy "Users can delete own manga"
on public.manga_library for delete
to authenticated
using (user_id = (auth.jwt() ->> 'sub'::text));

grant select, insert, update, delete on table public.manga_library to authenticated;
grant usage, select on sequence public.manga_library_id_seq to authenticated;
